version: 2

models:
  - name: stg_silver__patients
    description: "Staging model for the healthcare dataset."
    columns:
      - name: patient_id
        description: "Unique identifier for each patient."
        tests:
          - not_null
          - unique
      - name: sex
        description: "1 for female, 2 for male."
        tests:
          - not_null
      - name: age
        description: "Age of the patient."
        tests:
          - not_null
      - name: classification
        description: "Covid test findings. 1-3: diagnosed with covid, 4+: not a carrier or inconclusive."
      - name: patient_type
        description: "Type of care received. 1: returned home, 2: hospitalization."
        tests:
          - not_null
      - name: pneumonia
        description: "Whether the patient has air sacs inflammation. 1: yes, 2: no."
      - name: pregnant
        description: "Whether the patient is pregnant. 1: yes, 2: no."
      - name: diabetes
        description: "Whether the patient has diabetes. 1: yes, 2: no."
      - name: copd
        description: "Whether the patient has Chronic Obstructive Pulmonary Disease. 1: yes, 2: no."
      - name: asthma
        description: "Whether the patient has asthma. 1: yes, 2: no."
      - name: inmsupr
        description: "Whether the patient is immunosuppressed. 1: yes, 2: no."
      - name: hipertension
        description: "Whether the patient has hypertension. 1: yes, 2: no."
      - name: cardiovascular
        description: "Whether the patient has heart or blood vessel disease. 1: yes, 2: no."
      - name: renal_chronic
        description: "Whether the patient has chronic renal disease. 1: yes, 2: no."
      - name: other_disease
        description: "Whether the patient has other diseases. 1: yes, 2: no."
      - name: obesity
        description: "Whether the patient is obese. 1: yes, 2: no."
      - name: tobacco
        description: "Whether the patient is a tobacco user. 1: yes, 2: no."
      - name: usmer
        description: "Indicates whether the patient was treated in medical units of the first, second, or third level."
      - name: medical_unit
        description: "Type of institution of the National Health System that provided care."
      - name: intubed
        description: "Whether the patient was connected to a ventilator. 1: yes, 2: no."
      - name: icu
        description: "Whether the patient was admitted to an Intensive Care Unit. 1: yes, 2: no."
      - name: date_died
        description: "Date of death if the patient died, otherwise 9999-99-99."
