version: 2

sources:
  - name: covid19_dataset
    description: "Source for COVID-19 data from BigQuery"
    database: covidepidemetrics  # Replace with your GCP project ID
    schema: covid19_dataset    # BigQuery dataset name
    tables:
      - name: covid_data_from_gcs
        description: "Raw COVID-19 data loaded from Kaggle"
