version: 2

models:
  - name: fct__comorbidities_outcomes
    description: >
      Aggregated count of patients grouped by number of comorbidities and outcome
      (recovered or died). Comorbidity count is based on presence of various
      conditions (e.g., diabetes, hypertension).
    columns:
      - name: num_comorbidities
        description: Number of comorbidities a patient had.
        tests:
          - not_null
      - name: outcome
        description: Indicates whether the patient recovered or died.
        tests:
          - not_null
      - name: patient_count
        description: Number of patients with the specific comorbidity count and outcome.
        tests:
          - not_null

  - name: fct__deaths_age_time
    description: >
      Monthly and yearly counts of deaths, broken down by age group for
      hospitalized patients.
    columns:
      - name: age_group
        description: Age group classification of the patient.
        tests:
          - not_null
      - name: year
        description: Year of death.
        tests:
          - not_null
      - name: month
        description: Month of death.
        tests:
          - not_null
      - name: deaths
        description: Number of deaths for the given age group, year, and month.
        tests:
          - not_null

  - name: fct__deaths_recoveries_age
    description: >
      Total number of patients by patient type along with number of deaths and recoveries.
    columns:
      - name: patient_type
        description: Type of patient (e.g., outpatient, hospitalized).
        tests:
          - not_null
      - name: total_patients
        description: Total number of patients in that type.
        tests:
          - not_null
      - name: num_died
        description: Number of patients who died.
        tests:
          - not_null
      - name: num_recovered
        description: Number of patients who recovered (calculated).
        tests:
          - not_null

  - name: fct__recoveries_risk_age
    description: >
      Number of recovered patients broken down by risk level and age group.
    columns:
      - name: risk_level
        description: Risk classification of the patient.
        tests:
          - not_null
      - name: age_group
        description: Age group classification of the patient.
        tests:
          - not_null
      - name: total_patients
        description: Total number of patients in the group.
        tests:
          - not_null
      - name: num_recovered
        description: Number of patients who recovered.
        tests:
          - not_null
